// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      return ios;
        
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzN4RN14c12PVk-6nZ-5bOqv-j5i1f_Wk',
    appId: '1:681772466130:web:132a9780eee29ba2fe120b',
    messagingSenderId: '681772466130',
    projectId: 'nubank-98f35',
    authDomain: 'nubank-98f35.firebaseapp.com',
    storageBucket: 'nubank-98f35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6g41UeeCgyOinCUy3VlKdSM1yBOBEI_Y',
    appId: '1:681772466130:android:6076f66c4720c881fe120b',
    messagingSenderId: '681772466130',
    projectId: 'nubank-98f35',
    storageBucket: 'nubank-98f35.firebasestorage.app',
  );

static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6g41UeeCgyOinCUy3VlKdSM1yBOBEI_Y',
    appId: '1:681772466130:android:6076f66c4720c881fe120b',
    messagingSenderId: '681772466130',
    projectId: 'nubank-98f35',
    storageBucket: 'nubank-98f35.firebasestorage.app',
  );
}